apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-webapp
  labels: 
    app: employees
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      serviceAccountName: clo835
      containers:
        - name: e-webapp
          image: 360201675659.dkr.ecr.us-east-1.amazonaws.com/finalproject-webapp:v2.0
          ports: 
            - containerPort: 81
              protocol: TCP
          env:
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DBHOST
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: DBPORT
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: user
            - name: DBPWD 
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key : db-password
            - name: GROUP_NAME
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: GROUP_NAME
            - name: image
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: image
            - name: IMAGE_S3
              valueFrom:
                configMapKeyRef:
                  name: webapp-config
                  key: IMAGE_S3
            
            
